image: node:8

stages:
    - deploy

before_script:
    - npm install which
    - 'which ssh-agent || ( npm install openssh-clients)'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - npm ci

development:
    stage: deploy
    script:
        - npm run build --mode=development
        - ssh duratubp@eu1.getlark.com "rm -r -f www/dev.kapsalas-portfolio.eu/dist"
        - scp -v -C -r dist duratubp@eu1.getlark.com:www/dev.kapsalas-portfolio.eu
    except:
        - release
    environment: development


production:
    stage: deploy
    script:
        - npm run build
        - ssh duratubp@eu1.getlark.com "rm -r -f www/kapsalas-portfolio.eu/dist"
        - scp -C -r dist duratubp@eu1.getlark.com:www/kapsalas-portfolio.eu
    only:
        - release
    environment: production
